package com.example.tconfirmo.data.deposits

import com.google.gson.annotations.SerializedName

// Create/update payloads send the voucher content as Base64.
data class DepositCreateRequestDto(
    val cliente: String?,
    val empresaId: String?,
    val bancoId: String?,
    val imagenBase64: String
)

data class BatchDepositsRequestDto(
    val items: List<DepositCreateRequestDto>
)

data class BatchDepositsResponseDto(
    @SerializedName(value = "items", alternate = ["Items"])
    val items: List<BatchDepositCreateResultDto> = emptyList()
)

data class BatchDepositCreateResultDto(
    @SerializedName(value = "depositId", alternate = ["DepositId"])
    val depositId: String? = null,
    @SerializedName(value = "estado", alternate = ["Estado"])
    val estado: String? = null,
    @SerializedName(value = "error", alternate = ["Error"])
    val error: String? = null,
    @SerializedName(value = "index", alternate = ["Index"])
    val index: Int? = null
)

data class DepositCreateResponseDto(
    @SerializedName(value = "depositId", alternate = ["DepositId"])
    val depositId: String
)

data class DepositResponseDto(
    @SerializedName(value = "id", alternate = ["Id"])
    val id: String,
    @SerializedName(value = "numeroOperacion", alternate = ["NumeroOperacion"])
    val numeroOperacion: String,
    @SerializedName(value = "cliente", alternate = ["Cliente"])
    val cliente: String?,
    @SerializedName(value = "monto", alternate = ["Monto"])
    val monto: Double,
    @SerializedName(value = "moneda", alternate = ["Moneda"])
    val moneda: String,
    @SerializedName(value = "fechaRegistro", alternate = ["FechaRegistro"])
    val fechaRegistro: String,
    // Raw GCS object name. Kept only as fallback; UI should prefer imagenUrl.
    @SerializedName(value = "imagenVoucher", alternate = ["ImagenVoucher"])
    val imagenVoucher: String?,
    // Signed URL generated by the backend for private GCS vouchers.
    @SerializedName(value = "imagenUrl", alternate = ["ImagenUrl"])
    val imagenUrl: String?,
    @SerializedName(value = "anexo", alternate = ["Anexo"])
    val anexo: String?,
    @SerializedName(value = "numeroOperacionBanco", alternate = ["NumeroOperacionBanco"])
    val numeroOperacionBanco: String?,
    @SerializedName(value = "fechaDeposito", alternate = ["FechaDeposito"])
    val fechaDeposito: String?,
    @SerializedName(value = "estado", alternate = ["Estado"])
    val estado: String,
    @SerializedName(value = "observaciones", alternate = ["Observaciones"])
    val observaciones: String?,
    @SerializedName(value = "motivoRechazo", alternate = ["MotivoRechazo"])
    val motivoRechazo: String?,
    @SerializedName(value = "fechaValidacion", alternate = ["FechaValidacion"])
    val fechaValidacion: String?,
    @SerializedName(value = "empresaId", alternate = ["EmpresaId"])
    val empresaId: String?,
    @SerializedName(value = "bancoId", alternate = ["BancoId"])
    val bancoId: String?,
    @SerializedName(value = "sucursalId", alternate = ["SucursalId"])
    val sucursalId: String?,
    @SerializedName(value = "vendedorId", alternate = ["VendedorId"])
    val vendedorId: String,
    @SerializedName(value = "referenciaCliente", alternate = ["ReferenciaCliente"])
    val referenciaCliente: String?,
    @SerializedName(value = "datosOcr", alternate = ["DatosOcr"])
    val datosOcr: Any?,
    @SerializedName(value = "rucCliente", alternate = ["RucCliente"])
    val rucCliente: String?
)

data class DepositListResponseDto(
    @SerializedName(value = "id", alternate = ["Id"])
    val id: String,
    @SerializedName(value = "numeroOperacion", alternate = ["NumeroOperacion"])
    val numeroOperacion: String,
    @SerializedName(value = "cliente", alternate = ["Cliente"])
    val cliente: String?,
    @SerializedName(value = "monto", alternate = ["Monto"])
    val monto: Double,
    @SerializedName(value = "moneda", alternate = ["Moneda"])
    val moneda: String,
    @SerializedName(value = "fechaRegistro", alternate = ["FechaRegistro"])
    val fechaRegistro: String,
    @SerializedName(value = "estado", alternate = ["Estado"])
    val estado: String,
    @SerializedName(value = "numeroOperacionBanco", alternate = ["NumeroOperacionBanco"])
    val numeroOperacionBanco: String?,
    @SerializedName(value = "fechaDeposito", alternate = ["FechaDeposito"])
    val fechaDeposito: String?
)

data class DepositListPagedResponseDto(
    @SerializedName(value = "items", alternate = ["Items"])
    val items: List<DepositListResponseDto>,
    @SerializedName(value = "totalCount", alternate = ["TotalCount"])
    val totalCount: Int,
    @SerializedName(value = "page", alternate = ["Page"])
    val page: Int,
    @SerializedName(value = "pageSize", alternate = ["PageSize"])
    val pageSize: Int
)

data class BancoResponseDto(
    @SerializedName(value = "id", alternate = ["Id"])
    val id: String,
    @SerializedName(value = "nombre", alternate = ["Nombre"])
    val nombre: String,
    @SerializedName(value = "codigo", alternate = ["Codigo"])
    val codigo: String?
)

data class EmpresaResponseDto(
    @SerializedName(value = "id", alternate = ["Id"])
    val id: String,
    @SerializedName(value = "nombre", alternate = ["Nombre"])
    val nombre: String,
    @SerializedName(value = "logo", alternate = ["Logo"])
    val logo: String?,
    @SerializedName(value = "ruc", alternate = ["Ruc"])
    val ruc: String? = null,
    @SerializedName(value = "activo", alternate = ["Activo"])
    val activo: Boolean? = null
)
